pluginManagement {
    repositories {
        maven {
            name = 'Fabric-BMCL'
            url = 'https://bmclapi2.bangbang93.com/maven/'
        }
        maven {
            name = 'Fabric-Meta'
            url = 'https://meta.fabricmc.net/'
        }
        maven {
            name = 'Fabric-Meta-BMCL'
            url = 'https://bmclapi2.bangbang93.com/fabric-meta'
        }
        maven {
            name = 'Fabric-Hangbing_Proxy'
            url = "https://repository.hanbings.io/proxy"
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
rootProject.name = "shape-shifter-curse-addon"
