@echo off
setlocal enabledelayedexpansion
cd /d "%~dp0"
title Fabric Mod Build
echo ============ Fabric Mod Build ============
echo Dir: %CD%
echo.
if not exist "gradlew.bat"  ( echo [ERROR] gradlew.bat missing  ^& pause ^& exit /b 1 )
if not exist "build.gradle" ( echo [ERROR] build.gradle missing ^& pause ^& exit /b 1 )
set "B64="
for /f "usebackq tokens=* delims=" %%L in ("%~f0") do (
    set "LN=%%L"
    if "!LN:~0,5!"=="::B64" (
        set "REST=!LN:~5!"
        if defined B64 ( set "B64=!B64!!REST!" ) else ( set "B64=!REST!" )
    )
)
if not defined B64 ( echo [ERROR] PS body missing ^& pause ^& exit /b 1 )
set "RESOLVED=%TEMP%\ssc_resolved_jars.txt"
if exist "%RESOLVED%" del "%RESOLVED%"
set "SSC_RESOLVED_PATH=%RESOLVED%"
powershell -NoProfile -EncodedCommand "!B64!" 2>nul
set "ANY_UPSTREAM=0"
if exist "%RESOLVED%" (
    for /f "usebackq tokens=1,2,3 delims=|" %%A in ("%RESOLVED%") do (
        set "JAR=%%A"
        set "UROOT=%%B"
        set "EX=%%C"
        if not "!JAR!"=="" (
            set "ANY_UPSTREAM=1"
            echo [INFO] local dep jar: !JAR!
            if "!EX!"=="1" (
                echo      [OK] exists
            ) else (
                echo      [MISSING] build upstream: !UROOT!
                call :build_upstream "!JAR!" "!UROOT!"
                if errorlevel 1 (
                    del "%RESOLVED%" 2>nul
                    pause
                    exit /b 1
                )
            )
        )
    )
    del "%RESOLVED%" 2>nul
)
if "!ANY_UPSTREAM!"=="0" echo [INFO] No local files-jar dep found, skip upstream
echo.
echo ============ Build Self - clean build ============
call gradlew.bat clean build -x test
set "RC=!errorlevel!"
echo.
if "!RC!"=="0" (
    echo ============ BUILD SUCCESS ============
    if exist "build\libs" (
        echo Artifacts:
        set "MAIN="
        for %%f in ("build\libs\*.jar") do (
            echo    %%~nxf  ^(%%~zf bytes^)
            echo %%~nxf | findstr /i "sources" >nul
            if errorlevel 1 if not defined MAIN set "MAIN=%%f"
        )
        if defined MAIN echo Main jar: %CD%\!MAIN!
    )
    echo.
    pause
    exit /b 0
)
echo ============ BUILD FAILED ============
echo Common causes: compile error / mixin signature / dep jar missing / java version
where java
echo.
pause
exit /b 1
:build_upstream
set "JARP=%~1"
set "UROOT=%~2"
if not defined UROOT ( echo      [ERROR] no upstream root for: !JARP! ^& exit /b 1 )
pushd "!UROOT!" 2>nul
if errorlevel 1 ( popd 2>nul ^& echo      [ERROR] cannot locate upstream dir: !UROOT! ^& exit /b 1 )
set "UROOT_ABS=%CD%"
popd
if not exist "!UROOT_ABS!\gradlew.bat" ( echo      [ERROR] no gradlew.bat in: !UROOT_ABS! ^& exit /b 1 )
echo      [INFO] building upstream: !UROOT_ABS!
pushd "!UROOT_ABS!"
call gradlew.bat build -x test
set "UP_RC=!errorlevel!"
popd
if not "!UP_RC!"=="0" ( echo      [FAIL] upstream build failed: !UROOT_ABS! ^& exit /b 1 )
if not exist "!JARP!" ( echo      [WARN] upstream built but jar missing: !JARP! ^& exit /b 1 )
echo      [OK] upstream jar generated
exit /b 0
::B64WwBDAG8AbgBzAG8AbABlAF0AOgA6AE8AdQB0AHAAdQB0AEUAbgBjAG8AZABpAG4AZwAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBHAGUAdABFAG4AYwBvAGQAaQBuAGcAKAAnAEcAQgAxADgAMAAzADAAJwApAA0ACgAkAEUAcgByAG8AcgBBAGMAdABpAG8AbgBQAHIAZQBmAGUAcgBlAG4AYwBlACAAPQAgACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnAA0ACgAkAHUAdABmADgAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAEYAOAANAAoAJABvAHUAdAAgAD0AIAAkAGUAbgB2ADoAUwBTAEMAXwBSAEUAUwBPAEwAVgBFAEQAXwBQAEEAVABIAA0ACgBpAGYAIAAoAC0AbgBvAHQAIAAkAG8AdQB0ACkAIAB7ACAAJABvAHUAdAAgAD0AIAAnAC4AXABfAHIAZQBzAG8AbAB2AGUAZAAuAHQAeAB0ACcAIAB9AA0ACgAkAHIAZQBzAHUAbAB0AHMAIAA9ACAAQAAoACkADQAKACQAcAByAG8AcABzACAAPQAgAEAAewB9AA0ACgBpAGYAIAAoAFQAZQBzAHQALQBQAGEAdABoACAAJwBnAHIAYQBkAGwAZQAuAHAAcgBvAHAAZQByAHQAaQBlAHMAJwApACAAewANAAoAIAAgACAAIABbAFMAeQBzAHQAZQBtAC4ASQBPAC4ARgBpAGwAZQBdADoAOgBSAGUAYQBkAEEAbABsAEwAaQBuAGUAcwAoACcAZwByAGEAZABsAGUALgBwAHIAbwBwAGUAcgB0AGkAZQBzACcALAAgACQAdQB0AGYAOAApACAAfAAgAEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAAgAHsADQAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAXwAgAC0AbQBhAHQAYwBoACAAJwBeAFwAcwAqACgAWwBBAC0AWgBhAC0AegAwAC0AOQBfAC4ALQBdACsAKQBcAHMAKgA9AFwAcwAqACgALgArAD8AKQBcAHMAKgAkACcAKQAgAHsAIAAkAHAAcgBvAHAAcwBbACQAbQBhAHQAYwBoAGUAcwBbADEAXQBdACAAPQAgACQAbQBhAHQAYwBoAGUAcwBbADIAXQAgAH0ADQAKACAAIAAgACAAfQANAAoAfQANAAoAWwBTAHkAcwB0AGUAbQAuAEkATwAuAEYAaQBsAGUAXQA6ADoAUgBlAGEAZABBAGwAbABMAGkAbgBlAHMAKAAnAGIAdQBpAGwAZAAuAGcAcgBhAGQAbABlACcALAAgACQAdQB0AGYAOAApACAAfAAgAEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAAgAHsADQAKACAAIAAgACAAJABsAGkAbgBlACAAPQAgACQAXwANAAoAIAAgACAAIABpAGYAIAAoACQAbABpAG4AZQAgAC0AbQBhAHQAYwBoACAAJwBmAGkAbABlAHMAXABzACoAXAAoACcAIAAtAGEAbgBkACAAJABsAGkAbgBlACAALQBtAGEAdABjAGgAIAAnAFwALgBqAGEAcgAnACkAIAB7AA0ACgAgACAAIAAgACAAIAAgACAAJABtACAAPQAgAFsAcgBlAGcAZQB4AF0AOgA6AE0AYQB0AGMAaABlAHMAKAAkAGwAaQBuAGUALAAgACcAIgAoAFsAXgAiAF0AKwBcAC4AagBhAHIAWwBeACIAXQAqACkAIgAnACkADQAKACAAIAAgACAAIAAgACAAIABmAG8AcgBlAGEAYwBoACAAKAAkAG0AbQAgAGkAbgAgACQAbQApACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABwACAAPQAgACQAbQBtAC4ARwByAG8AdQBwAHMAWwAxAF0ALgBWAGEAbAB1AGUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGYAbwByAGUAYQBjAGgAIAAoACQAawAgAGkAbgAgACQAcAByAG8AcABzAC4ASwBlAHkAcwApACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHAAIAA9ACAAJABwACAALQByAGUAcABsAGEAYwBlACAAKAAnAFwAJABcAHsAcAByAG8AagBlAGMAdABcAC4AJwAgACsAIABbAHIAZQBnAGUAeABdADoAOgBFAHMAYwBhAHAAZQAoACQAawApACAAKwAgACcAXAB9ACcAKQAsACAAJABwAHIAbwBwAHMAWwAkAGsAXQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHAAIAA9ACAAJABwACAALQByAGUAcABsAGEAYwBlACAAKAAnAFwAJABcAHsAJwAgACsAIABbAHIAZQBnAGUAeABdADoAOgBFAHMAYwBhAHAAZQAoACQAawApACAAKwAgACcAXAB9ACcAKQAsACAAJABwAHIAbwBwAHMAWwAkAGsAXQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABwACAAPQAgACQAcAAgAC0AcgBlAHAAbABhAGMAZQAgACcALwAnACwAIAAnAFwAJwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABwACAAPQAgACQAcAAuAFQAcgBpAG0AKAApAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAcAApACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHUAcAAgAD0AIAAkAHAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABpAGQAeAAgAD0AIAAkAHUAcAAuAEkAbgBkAGUAeABPAGYAKAAnAGIAdQBpAGwAZABcAGwAaQBiAHMAJwApAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABpAGQAeAAgAC0AbAB0ACAAMAApACAAewAgACQAaQBkAHgAIAA9ACAAJAB1AHAALgBJAG4AZABlAHgATwBmACgAJwBiAHUAaQBsAGQAXAAnACkAIAB9AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABpAGQAeAAgAC0AZwBlACAAMAApACAAewAgACQAdQBwACAAPQAgACQAdQBwAC4AUwB1AGIAcwB0AHIAaQBuAGcAKAAwACwAIAAkAGkAZAB4ACkALgBUAHIAaQBtAEUAbgBkACgAJwBcACcAKQAgAH0ADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABlAHgAaQBzAHQAcwAgAD0AIABpAGYAIAAoAFQAZQBzAHQALQBQAGEAdABoACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAHAAKQAgAHsAIAAxACAAfQAgAGUAbABzAGUAIAB7ACAAMAAgAH0ADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJAByAGUAcwB1AGwAdABzACAAKwA9ACAAIgAkAHsAcAB9AHwAJAB7AHUAcAB9AHwAJAB7AGUAeABpAHMAdABzAH0AIgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQANAAoAIAAgACAAIAAgACAAIAAgAH0ADQAKACAAIAAgACAAfQANAAoAfQANAAoAIwAgACh1RwBCADEAOAAwADMAMACZUYdl9k4M/2MAbQBkACAAZgBvAHIAIAAvAGYA/YBja254+4sNAAoAWwBTAHkAcwB0AGUAbQAuAEkATwAuAEYAaQBsAGUAXQA6ADoAVwByAGkAdABlAEEAbABsAEwAaQBuAGUAcwAoACQAbwB1AHQALAAgACQAcgBlAHMAdQBsAHQAcwAsACAAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoARwBlAHQARQBuAGMAbwBkAGkAbgBnACgAJwBHAEIAMQA4ADAAMwAwACcAKQApAA0ACgA=
